class Image
  def initialize data, width, height
    @data = data
    @height = height
    @width = width
  end

  def self.from_pgm filepath
    File.open(filepath) do |file|
      header = file.readline
      unless header =~ /P5/
        raise 'Invalid PGM format. This program only accepts P5'
      end
      column_count, row_count = file.readline.split.map(&:to_i)
      file.readline
      data = file.read.unpack("C*")
      Image.new data, column_count, row_count
    end
  end

  def self.from_raw filepath, width, height
    File.open(filepath) do |file|
      data = file.read.unpack("C*")
      Image.new data, width, height
    end
  end

  # TODO clean up output
  def to_pgm(threshold)
    output = "P5\n"
    output << "# generated by example program for project 2\n"
    output << "#{width} #{height} \n"
    output << "255\n"
    if threshold < 10
      output << [255].pack("C")
    else
      output << [0].pack("C")
    end
    data_string = data.pack("C*")
    output << data_string[0...-1]
    output
  end

  def rows
    @_rows ||= (0...height).to_a.map do |row|
      data[row * width...(row+1)*width]
    end
  end
  attr_reader :data, :height, :width
end
